backend:
  name: git-gateway
media_folder: "images"
collections:
  - label: "Website Content"
    name: "website-content"
    editor:
      preview: false
    files:
      - label: "Home page"
        name: "home-page"
        file: "index.html"
        fields:
          - { label: "Body", name: "body", widget: "hidden" }
          # - { label: "Example field", name: "example-field", widget: "string" }
      - label: "Fuel price changes"
        name: "fuel-price-change"
        file: "_data/fuelprices.json"
        fields: 
          - { label: "Month", name: "month", widget: "string" }        
          - { label: "Diesel 50ppm", name: "d50Change", widget: "string" }        
          - { label: "ULP 93", name: "ulp93Change", widget: "string" }        
          - { label: "ULP 95", name: "ulp95Change", widget: "string" }        
          - { label: "Illuminating Paraffin", name: "ipChange", widget: "string" }   
          - { label: "Body", name: "body", widget: "hidden" }          
